name: "dev-kit"

services:
  traefik:
    image: "traefik:3.4"
    container_name: "dk-traefik"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./docker/traefik/certs:/etc/certs:ro"
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.app.loc`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

  buggregator:
    image: "ghcr.io/buggregator/server:latest"
    container_name: "dk-buggregator"
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025" # SMTP
      - "127.0.0.1:9912:9912" # Var-Dumper
      - "127.0.0.1:9913:9913" # Monolog
    networks:
      - "proxy"
      - "dev"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.buggregator.rule=Host(`${BUGGREGATOR_URL:-buggregator.app.loc}`)"
      - "traefik.http.services.buggregator.loadbalancer.server.port=8000"
      - "traefik.http.routers.buggregator.tls=true"

  dozzle:
    image: amir20/dozzle:latest
    container_name: "dt-dozzle"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle.rule=Host(`${DOZZLE_URL:-logs.app.loc}`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.tls=true"

networks:
  proxy:
    external: true
  dev:
    external: true
