name: "dev-kit"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "dk-traefik"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./docker/traefik/certs:/etc/certs:ro"
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.app.loc`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

networks:
  proxy:
    external: true
  dev:
    external: true
